export enum Type {
    NORMAL ="NORMAL",
    GHOST = "GHOST",
    GRASS = "GRASS",
    FIRE = "FIRE",
    WATER = "WATER",
    PSYCHIC = "PSYCHIC",
    ACIER = "ACIER",
    FLYING = "FLYING",
    GROUND = "GROUND",
    ROCK = "ROCK",
    ICE = "ICE",
    ELECTRIC = "ELECTRIC",
    INSECTE = "INSECTE",
    DARK = "DARK",
    DRAGON = "DRAGON",
    POISON = "POISON",
    BUG = "BUG",
    STEEL = "STEEL",
    FIGHTING = "FIGHTING"
}